import { chromium } from 'playwright'
const CHROME = `${process.env.HOME}/Library/Caches/ms-playwright/chromium-1223/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing`
const browser = await chromium.launch({ executablePath: CHROME })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 })
await page.goto('http://localhost:5180', { waitUntil: 'networkidle' })
await page.waitForTimeout(900)
await page.locator('button[aria-label*="focus timer" i]').first().click()
await page.waitForTimeout(600)
console.log('timer text:', (await page.locator('aside[aria-label="Focus timer"]').innerText()).split('\n').slice(0, 4).join(' | '))
await page.locator('button:has-text("Start")').first().click()
await page.waitForTimeout(1500)
console.log('after start:', (await page.locator('aside[aria-label="Focus timer"]').innerText()).split('\n').slice(0, 4).join(' | '))
console.log('title:', await page.title())
await page.locator('button[aria-label="Close timer"]').click()
await page.waitForTimeout(1200)
console.log('pill:', await page.locator('button[aria-label*="focus timer" i]').first().innerText())
await page.locator('button[aria-label*="focus timer" i]').first().click()
await page.waitForTimeout(300)
await page.screenshot({ path: '/tmp/tempo-final2.png' })
await browser.close()